FROM          salt-minion:latest
MAINTAINER    Khris Richardson <khris.richardson@gmail.com>

EXPOSE        6789
EXPOSE        6800
EXPOSE        6801
EXPOSE        6802
EXPOSE        6803
EXPOSE        6804
EXPOSE        6805
EXPOSE        6806
EXPOSE        6807
EXPOSE        6808
EXPOSE        6809
EXPOSE        6810
