FROM          salt-minion:latest
MAINTAINER    Khris Richardson <khris.richardson@gmail.com>

EXPOSE        2181
EXPOSE        2888
EXPOSE        3181
EXPOSE        3888
EXPOSE        4181
EXPOSE        9000
EXPOSE        9010
