FROM          salt-minion:latest
MAINTAINER    Khris Richardson <khris.richardson@gmail.com>

EXPOSE        24007
EXPOSE        24008
EXPOSE        24009
EXPOSE        34865
EXPOSE        34866
EXPOSE        34867
