FROM          salt-minion:latest
MAINTAINER    Khris Richardson <khris.richardson@gmail.com>

EXPOSE        1004
EXPOSE        1006
EXPOSE        9000
EXPOSE        50010
EXPOSE        50020
EXPOSE        50075
EXPOSE        50475
